[header]
pdb_file_name = "ntkrnlmp.pdb"
pdb_guid = "0AFB69F5FD264D54673570E37B38A3181"
nt_major_version = 10
nt_minor_version = 0
nt_build_number = 18362
arch = "X64"

[offsets]
list_blink = 8
eproc_link = 752
phys_mem_block = 5719112
kproc_dtb = 40
eproc_pid = 744
eproc_name = 1104
eproc_peb = 1016
eproc_section_base = 968
eproc_exit_status = 1620
eproc_thread_list = 1160
eproc_wow64 = 1064
eproc_vad_root = 1624
kthread_teb = 240
ethread_list_entry = 1720
teb_peb = 96
teb_peb_x86 = 48

[offsets.mmvad]
vad_node = 0
starting_vpn = 24
ending_vpn = 28
starting_vpn_high = 32
ending_vpn_high = 33
u = 48
protection_bit = 7
