[header]
pdb_file_name = "ntkrpamp.pdb"
pdb_guid = "1B1D6AA205E1C87DC63A314ACAA50B491"
nt_major_version = 10
nt_minor_version = 0
nt_build_number = 19041
arch = "X86"

[offsets]
list_blink = 4
eproc_link = 232
phys_mem_block = 3225556
kproc_dtb = 24
eproc_pid = 228
eproc_name = 428
eproc_peb = 380
eproc_section_base = 352
eproc_exit_status = 844
eproc_thread_list = 464
eproc_wow64 = 0
eproc_vad_root = 848
kthread_teb = 168
ethread_list_entry = 740
teb_peb = 48
teb_peb_x86 = 48

[offsets.mmvad]
vad_node = 0
starting_vpn = 12
ending_vpn = 16
starting_vpn_high = 0
ending_vpn_high = 0
u = 28
protection_bit = 7
