name: Build and test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        flags: [--all-features, --no-default-features]
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo build --workspace ${{ matrix.flags }} --verbose

      - name: Build examples
        run: cargo build --workspace ${{ matrix.flags }} --examples --verbose

  build-cross-targets:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --workspace --all-features --verbose

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Pre-build binaries (for inventory integration tests)
        run: cargo build --workspace --all-features --verbose

      - name: Run all tests
        run: cargo test --workspace --all-features --verbose
        if: runner.os == 'Linux'

      - name: Run all tests
        run: cargo test --workspace --exclude memflow-derive --all-features --verbose
        if: runner.os != 'Linux'

  test-cross:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-unknown-linux-gnu, i686-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: Pre-build binaries (for inventory integration tests)
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --workspace --all-features --verbose --release
      - name: Run all tests
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: -Zdoctest-xcompile --target ${{ matrix.target }} --workspace --all-features --verbose --release

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Check formatting
        run: cargo fmt -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features

